### PR TITLE
Some support for windows

### PR DESCRIPTION
**Pull request by AllNamesRTaken**
changed case to pcase since they didnt work on emacs for windows (win8.1)
also changed ' to ` in one region since ' didnt work but ` did.

Another error.
cannot use M-. since the function called uses a function named "first" but on emacs for windows atleast that function does not exist. C-h first does not know of it.

### CODE REVIEW

**Comment by reactormonk** [comment]
https://github.com/reactormonk/nim-mode/commit/77ab3aaaed1fa1b8a3e63146b97a6a2c8b6e26a3 should work instead

**Comment by AllNamesRTaken** [comment]
Now the FIRST function doesnt crash any more but I keep getting Lisp nesting exceeds `max-lisp-eval-depth when I call M-.

Any clue what that might come from?

**Comment by reactormonk** [comment]
Yes, I'm not running `(require 'cl)`.

**Comment by AllNamesRTaken** [comment]
That worked too instead of the first-wrapper but also didnt solve the error: Lisp nesting exceeds `max-lisp-eval-depth

Maybe its better to just wrapp first instead of require cl?

**Comment by reactormonk** [comment]
Ok, I added `eval-and-compile` then. I don't like duplicated code. Does it work without the custom `first`?

**Comment by AllNamesRTaken** [comment]
sure no problem!
But as I said.. still get the error.

**Comment by reactormonk** [comment]
I don't get the error when I load it, what is you `max-lisp-eval-depth`? I have a standard of 600. Maybe try a larger size and see if it's an infinite recursion somewhere?

**Comment by AllNamesRTaken** [comment]
My guess is an infinite loop. When I increase it to 1800 i just get the same error on max-specpdl-size. And increasing that from 1300 to 3300 just brings me back to the first error

**Comment by reactormonk** [comment]
Since I can't reproduce it, could you put `(message "foo")` at various points in the code and tell me where it occurs?

**Comment by AllNamesRTaken** [comment]
no problem!
ill do it tomorrow.. getting late

**Comment by AllNamesRTaken** [comment]
It seemed that you rely on finding a .nim.cfg or you will loop infinitely, and I hade an old .nimrod.cfg.
When I fixed that it doesnt loop but I get:
Wrote c:/Users/XXX/AppData/Local/Temp/nim-suggest12580MrT/sdl_handmade.nim
progn: Symbol not found 

regardless where I do M-.
maybe I am just missing something else in the setup.

The function looping was nim-find-file-in-heirarchy

**Comment by reactormonk** [comment]
Yeah, the symbol auto completion is a bit broken atm, I'm still waiting on upstream changes.

**Comment by AllNamesRTaken** [comment]
Which commands do work for you if not M-. ?
Also in my emacs the indentation is indenting the previous row when I press enter which is really irritating when you want to leave a block, backspace to dedent, start a new expression and it all jumps back out when I press enter. Is that intentional, not happening in your solution (perhaps a collision with my .emacs) or something you also wish you didnt have?

**Comment by reactormonk** [comment]
That's a different issue. https://github.com/reactormonk/nim-mode/issues/19

**Pull request closed without merging**
